# -*- coding: utf-8 -*-
"""test_assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10EglxZ8y8EdWuhfKecq9O9brmpqwdWtU
"""

import os
import nbformat
from nbconvert.preprocessors import ExecutePreprocessor

def test_notebook_execution():
    with open("assignment.ipynb") as f:
        nb = nbformat.read(f, as_version=4)
    ep = ExecutePreprocessor(timeout=300)
    ep.preprocess(nb, {'metadata': {'path': './'}})

    # Check for expected variable (e.g., accuracy)
    ns = {}
    exec("\n".join([cell['source'] for cell in nb.cells if cell.cell_type == 'code']), ns)
    assert 'accuracy' in ns, "Variable 'accuracy' not found"
    assert ns['accuracy'] >= 0.75, "Accuracy too low"